name: .NET Build and Upload Artifact

on:
  push:
    branches:
      - develop-next
  pull_request:
    branches:
      - develop-next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Linux version (x64)
        run: dotnet publish --configuration Release --runtime linux-x64 --output ./output/linux/x64

      - name: Publish Linux version (arm64)
        run: dotnet publish --configuration Release --runtime linux-arm64 --output ./output/linux/arm64

      - name: Publish Windows version
        run: dotnet publish --configuration Release --runtime win-x64 --output ./output/windows

      - name: Upload Linux x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x64
          path: ./output/linux/x64

      - name: Upload Linux arm64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-arm64
          path: ./output/linux/arm64

      - name: Upload Windows x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64
          path: ./output/windows